"""Initial database setup

Revision ID: d0f109f36640
Revises: 
Create Date: 2025-06-22 17:16:48.492514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f109f36640'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('token_address', sa.String(), nullable=False),
    sa.Column('token_name', sa.String(), nullable=False),
    sa.Column('token_ticker', sa.String(), nullable=False),
    sa.Column('price_sol', sa.Float(), nullable=False),
    sa.Column('market_cap_sol', sa.Float(), nullable=False),
    sa.Column('volume_sol', sa.Float(), nullable=False),
    sa.Column('liquidity_sol', sa.Float(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('price_1hr_change', sa.Float(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token_address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###
